apiVersion: v1
data:
  clearpass_config.py: |
    URL = ""
    CHECK_SSL = False
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: vectra-automated-response
  name: clearpass
