apiVersion: v1
data:
  harmony_config.py: |
    AUTH_URL = ""
    CHECK_SSL = False
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: vectra-automated-response
  name: harmony
