apiVersion: v1
data:
  meraki_config.py: |
    MERAKI_URL = "https://api.meraki.com/api/v1"
    # Define to use a custom Group Policy vs default 'Blocked'
    BLOCK_GROUP_POLICY = ""
    PORT_SCHEDULE = "Block"
    BLOCK_MULTIPLE_MAC = True
    BLOCK_MULTIPLE_IP = False
    BLOCK_INACTIVE_CLIENTS = True
    CHECK_SSL = False
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: vectra-automated-response
  name: meraki
