apiVersion: v1
data:
  sophos_edr_config.py: |
    WHOAMI_URL = "https://api.central.sophos.com/whoami/v1"
    AUTH_URL = "https://id.sophos.com/api/v2/oauth2/token"
    VERIFY = False
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: vectra-automated-response
  name: sophos-edr
