apiVersion: v1
data:
  tanium_config.py: |-
    URL = ""
    BLOCK_PKG = []
    UNBLOCK_PKG = []
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: vectra-automated-response
  name: tanium
