apiVersion: v1
data:
  vision_one_config.py: |
    BASE_URL = "https://api.<region>.xdr.trendmicro.com"
    CHECK_SSL = False
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: vectra-automated-response
  name: trendmicro-vision-one
